### ISSUE TITLE
Installer delay after clicking selecting "All Users"

### ISSUE THREAD

**Issue by phurley** [wpilibsuite/WPILibInstaller#8]
It takes almost 10 seconds on a reasonably fast (3Ghz I7, SSD) machine for the auth dialog to appear. During this time it is easy to click the button multiple times, leading to multiple auth dialogs and some confusion.

At the very least disable the buttons after clicking to prevent the confusion -- pretty much every one of our students did this.

Not a major issue.

**Comment by PeterJohnson** [comment]
My working theory is the delay is due to the size of the installer executable--what I think is happening is when privilege escalation happens, Windows copies the entire executable to a privileged area, and that's what takes a long time.  My suggested fix is to copy just the actual installer executable part (which is much smaller) to a temporary file and run it as a subprocess (using the original installer as a data file e.g. by passing its path as a command line option), then do the privilege escalation in the subprocess.
